### PR TITLE
Track default changes

### PR DESCRIPTION
**Pull request by Bnaya**
I've add this small mod
If its a valid feature from your point of you i can make a proper PR

Thanks for that great library!!

### CODE REVIEW

**Comment by tannerlinsley** [comment]
What does it do?

**Comment by Bnaya** [comment]
Its allows to change the starting point of the animation (the defaults object) and not only the ending point

**Comment by Bnaya** [comment]
With more words:
Now, the library using the defaults prop only for the initial tweening.
When changing the data again, it will tween the values from the old state of data to the new one that provided.

In my use case, (scrolling of react virtualized grid), the current state of the scroll is changing internally, so i need to tell the Animate component to start the tweening from a new position.

I did it quickly for my self on that branch, but the api can be done more clear.

If you will want to add it to the lib, we can think on a more clear api for that (maybe another prop? or changing the prop "default" to something more meaningful for that context)

**Comment by tannerlinsley** [comment]
This is an interesting concept.  So if I understand you correctly, you basically want the effect as if the Animate component had unmounted and mounted again, thus "jumping" to the new default state immediately, then animating to the desired state.  For now, you could actually do just that, but I understand that unmounting could incur some bad perf. 

I would be fine merging this, but we'll need to update a few things first. I'll leave notes in a review for you.

**Comment by Bnaya** [comment]
Thanks!
indeed unmounting is not an option with my use case 
As you can see its a very simple patch
You can just implement it on the way you think is best

**Comment by Bnaya** [comment]
ping @tannerlinsley I really want to get rid of my fork :)

**Comment by tannerlinsley** [comment]
Due to react-move's merge with resonance, this may not be necessary any more. Reopen if you find it necessary :) We will be launching version 2.0 very soon.

**Comment by Bnaya** [comment]
Ok, waiting for it!

**Pull request closed without merging**
